### ISSUE TITLE
Error 502 - The server encountered a temporary error and could not complete your request

### ISSUE THREAD

**Issue by bealdav** [akretion/connector-google-spreadsheet#5]
Traceback (most recent call last):
  File "/workspace/parts/connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/workspace/parts/connector/connector/queue/job.py", line 466, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/workspace/parts/connector-google-spreadsheet/connector_google_spreadsheet/google_spreadsheet.py", line 391, in import_document
    error_cells = sheet.range(start + ':' + stop)
  File "/home/dav/.voodoo/shared/eggs/gspread-0.2.5-py2.7.egg/gspread/models.py", line 334, in range
    'return-empty': 'true'})
  File "/home/dav/.voodoo/shared/eggs/gspread-0.2.5-py2.7.egg/gspread/client.py", line 250, in get_cells_feed
    r = self.session.get(url)
  File "/home/dav/.voodoo/shared/eggs/gspread-0.2.5-py2.7.egg/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, *_kwargs)
  File "/home/dav/.voodoo/shared/eggs/gspread-0.2.5-py2.7.egg/gspread/httpsession.py", line 75, in request
    raise HTTPError("%s: %s" % (response.status, response.read()))
HTTPError: 502: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}_ > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

**Comment by bealdav** [comment]
Here is a PR
https://github.com/akretion/connector-google-spreadsheet/pull/6
